
export const ALGORITHM_NAMES = {
	COUNTING_SORT: 'Countin Sort',
	RADIX_SORT: 'Radix Sort',
	BUCKET_SORT: 'Bucket sort',
};

export const ALGORITHM_NAMES_ARR = [
	ALGORITHM_NAMES.COUNTING_SORT,
	ALGORITHM_NAMES.BUCKET_SORT,
	ALGORITHM_NAMES.RADIX_SORT,
];